[workspace]
  resolver = "2"
  members = [
    "crates/*",
    "examples/*",
  ]
  include = [
    "README.md"
  ]
  exclude = [
    "promo/*",
    "examples/*",
    ".gitignore",
    ".vscode",
  ]

[profile.dev]
  opt-level = 1

[workspace.package]
  authors     = ["Dominik Kaspar"]
  version     = "0.1.0-alpha"
  edition     = "2021"
  license     = "MIT OR Apache-2.0"
  repository  = "https://github.com/bytestring-net/bevy-lunex"
  keywords    = ["ui", "layout", "bevy", "lunex", "bevy-lunex"]
  categories  = ["gui", "mathematics", "game-development"]

[workspace.dependencies]

  bevy_lunex   = { path = "crates/bevy_lunex", version = "0.1.0-alpha" }
  lunex_engine = { path = "crates/lunex_engine", version = "0.1.0-alpha" }

  colored            = { version = "^2.1" }
  indexmap           = { version = "^2.1" }
  thiserror          = { version = "^1.0" }

  bevy = { version = "0.13.2", default_features = false, features = [
    #"bevy_asset",
    #"bevy_gilrs",
    "bevy_pbr",
    "bevy_sprite",
    "bevy_text",
    "multi-threaded",
    "bevy_gizmos",
  ] }

  bevy_mod_picking = { version = "0.18.2", default_features = false, features = [] }